In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
pd.__version__

'3.0.6'

In [36]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")

In [5]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [6]:
df.info

<bound method DataFrame.info of       model_year  origin fuel_type         drivetrain  num_doors  \
0           2006  Europe  Gasoline  Front-wheel drive          4
1           2008  Europe    Diesel  Front-wheel drive          4
2           1996    Asia  Gasoline  Front-wheel drive          5
3           1989  Europe  Gasoline  Front-wheel drive          4
4           1994     USA    Diesel  Front-wheel drive          3
...          ...     ...       ...                ...        ...
9995        2005     USA  Gasoline    All-wheel drive          4
9996        1993    Asia  Gasoline    All-wheel drive          2
9997        2014     USA  Gasoline    All-wheel drive          3
9998        2004     USA    Hybrid   Rear-wheel drive          5
9999        2011     USA    Diesel  Front-wheel drive          4

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                    2180              6       243.0            3870
1                    2390              6       272.0            4210
2                    2320              6       267.0            4240
3                    2130              6       258.0            4490
4                    2580              7       304.0            4510
...                   ...            ...         ...             ...
9995                 2470              6       271.0            4690
9996                 2300              6       244.0            4370
9997                 2480              6       267.0            4590
9998                 2180              6       270.0            4450
9999                 2380              6       295.0            4370

      acceleration  fuel_efficiency_mpg
0              NaN                 31.9
1              NaN                 31.3
2             17.3                 27.5
3             18.7                 28.5
4             17.5                 31.0
...            ...                  ...
9995          18.9                 27.4
9996          19.0                 30.0
9997          18.4                 28.1
9998          20.9                 32.2
9999          17.6                 30.2

[10000 rows x 11 columns]>

Get the Shape (Rows x Columns) of the data

In [6]:
df.shape

(10000, 11)

Get Fuel Types

In [8]:
df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

Get missing values

In [37]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

Max Fuel Efficienty of Cars from Asia

In [16]:
df[df['origin'] =='Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

Median value of horse power

In [38]:
df['horsepower'].median()

np.float64(254.0)

In [42]:
df['horsepower'].isna().sum()

np.int64(0)

Find most frequent value

In [40]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [41]:
df['horsepower'] = df['horsepower'].fillna(252.0)

In [43]:
df['horsepower'].median()

np.float64(252.0)

Sum of Weights

In [45]:
df1 = df[df['origin'] == 'Asia']
df1.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [54]:
array2d = df1[['vehicle_weight', 'model_year']]
array2d.shape

(2994, 2)

In [55]:
array2d.head()

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007

In [63]:
X = array2d[0:7].to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [65]:
XT= np.transpose(X)

In [80]:
transposed = X.T

In [75]:
res = X.T @ X
res

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [73]:
inv = np.linalg.inv(res)

In [74]:
inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [77]:
inv.shape

(2, 2)

In [78]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [85]:
w = np.matmul(np.matmul(inv, transposed), y)

In [86]:
w

array([0.13644777, 0.2327492 ])

In [88]:
w.sum()

np.float64(0.36919696904925203)